use super::types::idl_type_to_rust;
use anyhow::Result;
use heck::{ToPascalCase, ToSnakeCase};
use shank_idl::idl_type_definition::{IdlTypeDefinition, IdlTypeDefinitionTy};

pub fn account_rs(account: &IdlTypeDefinition) -> Result<String> {
    let name = account.name.to_pascal_case();
    let fields = match &account.ty {
        IdlTypeDefinitionTy::Struct { fields } => fields,
        IdlTypeDefinitionTy::Enum { .. } => {
            anyhow::bail!("pinoc client generate does not support enum accounts yet ({name})")
        }
    };

    let mut field_lines = String::new();
    for field in fields {
        let field_name = field.name.to_snake_case();
        let field_ty = idl_type_to_rust(&field.ty)?;
        field_lines.push_str(&format!("    pub {field_name}: {field_ty},\n"));
    }

    Ok(format!(
        r#"//! Autogenerated by `pinoc client generate`. Do not edit by hand.

use borsh::{{BorshDeserialize, BorshSerialize}};

#[derive(BorshSerialize, BorshDeserialize, Clone, Copy, Debug, PartialEq)]
pub struct {name} {{
{field_lines}}}

impl {name} {{
    pub fn from_bytes(data: &[u8]) -> std::io::Result<Self> {{
        let mut data = data;
        <Self as BorshDeserialize>::deserialize(&mut data)
    }}

    pub fn to_bytes(&self) -> std::io::Result<Vec<u8>> {{
        borsh::to_vec(self)
    }}
}}
"#
    ))
}
