pub fn shared_rs() -> String {
    r#"//! Autogenerated by `pinoc client generate`. Do not edit by hand.

#[cfg(feature = "fetch")]
#[derive(Debug, Clone)]
pub struct DecodedAccount<T> {
    pub address: solana_address::Address,
    pub account: solana_account::Account,
    pub data: T,
}

#[cfg(feature = "fetch")]
#[derive(Debug, Clone)]
pub enum MaybeAccount<T> {
    Exists(DecodedAccount<T>),
    NotFound(solana_address::Address),
}
"#
    .to_string()
}
