use anyhow::Result;
use heck::{ToPascalCase, ToSnakeCase};
use shank_idl::idl_type::IdlType;
use shank_idl::idl_type_definition::{IdlTypeDefinition, IdlTypeDefinitionTy};

pub fn idl_type_to_rust(ty: &IdlType) -> Result<String> {
    Ok(match ty {
        IdlType::U8 => "u8".to_string(),
        IdlType::U16 => "u16".to_string(),
        IdlType::U32 => "u32".to_string(),
        IdlType::U64 => "u64".to_string(),
        IdlType::U128 => "u128".to_string(),
        IdlType::I8 => "i8".to_string(),
        IdlType::I16 => "i16".to_string(),
        IdlType::I32 => "i32".to_string(),
        IdlType::I64 => "i64".to_string(),
        IdlType::I128 => "i128".to_string(),
        IdlType::Bool => "bool".to_string(),
        IdlType::String => "String".to_string(),
        IdlType::PublicKey => "solana_pubkey::Pubkey".to_string(),
        // shank's `#[idl_type("publicKey")]` field override produces a
        // `Defined("publicKey")` reference rather than the `IdlType::PublicKey`
        // variant, and pinocchio's own `Address` type shows up as `Defined("Address")`
        // since shank doesn't know it's a pubkey type. Both mean the same thing.
        IdlType::Defined(name) if name == "Address" || name.eq_ignore_ascii_case("publicKey") => {
            "solana_pubkey::Pubkey".to_string()
        }
        IdlType::Defined(name) => name.to_pascal_case(),
        IdlType::Array(inner, size) => format!("[{}; {size}]", idl_type_to_rust(inner)?),
        IdlType::Vec(inner) => format!("Vec<{}>", idl_type_to_rust(inner)?),
        IdlType::Option(inner) => format!("Option<{}>", idl_type_to_rust(inner)?),
        other => anyhow::bail!("pinoc client generate does not support the IDL type {other:?} yet"),
    })
}

pub fn type_def_rs(ty_def: &IdlTypeDefinition) -> Result<String> {
    let name = ty_def.name.to_pascal_case();
    let fields = match &ty_def.ty {
        IdlTypeDefinitionTy::Struct { fields } => fields,
        IdlTypeDefinitionTy::Enum { .. } => {
            anyhow::bail!("pinoc client generate does not support enum types yet ({name})")
        }
    };

    let mut field_lines = String::new();
    for field in fields {
        let field_name = field.name.to_snake_case();
        let field_ty = idl_type_to_rust(&field.ty)?;
        field_lines.push_str(&format!("    pub {field_name}: {field_ty},\n"));
    }

    Ok(format!(
        r#"//! Autogenerated by `pinoc client generate`. Do not edit by hand.

use borsh::{{BorshDeserialize, BorshSerialize}};

#[derive(BorshSerialize, BorshDeserialize, Clone, Copy, Debug, PartialEq)]
pub struct {name} {{
{field_lines}}}
"#
    ))
}
