pub fn cargo_toml(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}-client"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = {{ version = "1", features = ["derive"] }}
solana-pubkey = "4.2"
solana-instruction = "3.4"
solana-address = {{ version = "2.6", features = ["decode", "borsh"] }}
"#
    )
}

pub fn lib_rs(program_address: &str) -> String {
    format!(
        r#"#![allow(clippy::all)]
//! This code was autogenerated by `pinoc client generate` from the program's
//! shank IDL. Do not edit by hand; rerun `pinoc client generate` instead.

pub mod generated;
pub use generated::*;

solana_pubkey::declare_id!("{program_address}");
"#
    )
}
